name: flutter_graphql_client
description: Client to POST to GraphQL server
version: 0.2.0
homepage: https://github.com/savannahghi/flutter_graphql_client
repository: https://github.com/savannahghi/flutter_graphql_client
issue_tracker: https://github.com/savannahghi/flutter_graphql_client/issues
documentation: https://github.com/savannahghi/flutter_graphql_client/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  gql: ^0.13.0
  http: ^0.13.3
  meta: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  platform: ^3.1.0
  source_span: ^1.8.0
  sqflite: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10
  test:
  test_api: ">=0.2.19"

flutter: null
