name: sil_graphql_client
description: Client to POST to GraphQL server
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:
  sdk: '>=2.12.0 <3.0.0'  
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter  
  gql: ^0.13.0
  http: ^0.13.3
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3 
dev_dependencies: 
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3 
  mockito: ^5.0.10   
  test:
  test_api: '>=0.2.19'


flutter: null
