name: sil_graphql_client
description: Client to POST to GraphQL server
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:
  sdk: '>=2.12.0 <3.0.0'  
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter  
  gql: ^0.13.0-nullsafety.2
  http: ^0.13.0
  path_provider: ^2.0.1  
  sqflite: ^2.0.0+2  
dev_dependencies: 
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  lint: ^1.0.0 
  mockito: ^5.0.0   
  test:
  test_api: '>=0.2.19'


flutter: null
